# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  一泓清波
subtitle: 他山之石，可以攻玉
name: 一泓清波 
email: 1165473778@qq.com
description: 本站是一泓清波的技术分享博客。内容涵盖生活故事、Java后端技术、Spring Boot、Spring Cloud、微服务架构、大数据演进、高可用架构、中间件使用、系统监控等相关的研究与知识分享。
keywords: yihongqingbo,一泓清波,Spring,Spring Boot,Spring Cloud,MongoDB,Jvm,Docker,生活故事,架构,大数据,一线,FastDFS,开发者,编程,代码,开源,IT网站,Developer,Programmer,Coder,Geek,IT技术博客,Java,Python,
encoding: "utf-8"
favicon: favicon.png 

repository: yihongqingbo/yihongqingbo.github.io
github_url: https://github.com/yihongqingbo
cnblog_url: http://www.cnblogs.com/yihongqingbo
url: http://yihongqingbo.github.io
enforce_ssl: yihongqingbo.github.io

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata
  - jekyll-octicons
  
# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
# ---------------- #
#       RSS        #
# ---------------- #
navs:

  -
    href: /
    label: Home

  -
    href: /baby.html
    label: baby
    
  -
    href: /life.html
    label: life
 #
 # -
 #   href: /spring-cloud.html
 #   label: Spring-Cloud
 #
 #-
 #   href: /archives.html
 #  label: Archives

 # -
 #   href: /link.html
 #  label: Link

 # -
 #   href: /about.html
 #   label: About


# labels. my blog key words
labels:

  -
    href: /share/2017/10/01/resource-sharing.html
    name: 资源

  -
    href: /life.html
    name: 故事

  -
    href: /arch.html
    name: 架构
    
  -
    href: /jvm.html
    name: Jvm

  -
    href: /fastdfs.html
    name: FastDFS

  -
    href: /mongodb.html
    name: MongoDB

  -
    href: /docker.html
    name: Docker

  -
    href: /open-source.html
    name: Code   

# selected articles

classes:

  -
    href: /web.html
    name: 前端技术分享
    describe: 输出就有结果，简单明了

  -
    href: /bigData.html
    name: 大数据技术点
    describe: 拼凑出大数据画面

  -
    href: /books.html
    name: 读书解惑
    describe: 生活充满困惑，书中给出答案


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: yihongqingbo
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: yihongqingbo
    repo: blog-comments
    oauth:
        client_id: f06f73519e4556b853bb
        client_secret: 251435dc07e3d5d1c06839ae441bdce7ed7f5479
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: yihongqingbo
    repo: blog-comments
    clientID: f06f73519e4556b853bb
    clientSecret: 251435dc07e3d5d1c06839ae441bdce7ed7f5479
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true
